name: outputs_demo

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'
      
      - name: Run Python script and create hello.txt
        id: python_script
        run: |
          echo "Hello, World" > hello.txt  # Ensuring hello.txt is created
          python src/main.py  # Assuming this is where hello.txt is generated

      - name: Debug check for hello.txt
        run: ls -la   # List directory contents to confirm the file exists

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: hello.txt  # Uploading hello.txt directly

  job3:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: my-artifact  # Ensures artifact name matches job1's upload

      - name: Verify Artifact Content
        run: |
          cat hello.txt  # Display content of downloaded hello.txt

  test-run:
    runs-on: ubuntu-latest
    needs: job3
    steps:
      - name: Download candidate artifacts
        uses: actions/download-artifact@v3
        with:
          name: my-artifact
          
      - run: |
          cat hello.txt  # Check content to confirm artifact was downloaded
