name: Python application

on: 
  push:
    branches:
      - main  # Trigger on push to main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Checkout the repository to the runner

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.2'  # Specify the Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # Upgrade pip
        pip install -r requirements.txt      # Install dependencies from requirements.txt

    - name: Run the script
      run: |
        python src/main.py  # Run your Python script

    - name: Upload training output
      uses: actions/upload-artifact@v3
      with:
        name: training-output
        path: training_output/  # Archive the training output directory

    - name: Upload HTML report
      uses: actions/upload-artifact@v3
      with:
        name: html-report
        path: html_output/  # Archive the HTML report directory
