name: outputs_demo

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    
    steps:
      - id: step1
        run: |
          echo "output1=hello" >> $GITHUB_ENV
          
      - id: step2
        run: |
          echo "output2=world" >> $GITHUB_ENV
      
      - id: step3
        run: |
          tagvar=test12345
          echo "output3=$tagvar" >> $GITHUB_ENV
      
      - name: Checkout branch
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'
      
      - name: Run python script
        id: python_script
        run: |
          python src/main.py
          contents=$(cat hello.txt)
          echo "output4=$contents" >> $GITHUB_ENV
      
      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3.14.0

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact  # Upload artifact as "my-artifact"
          path: hello.txt

    outputs:
      output1: ${{ steps.step1.outputs.output1 }}
      output2: ${{ steps.step2.outputs.output2 }}
      output3: ${{ steps.step3.outputs.output3 }}
      output4: ${{ steps.python_script.outputs.output4 }}
      changelog: ${{ steps.changelog.outputs.changelog }}
      clean_changelog: ${{ steps.changelog.outputs.clean_changelog }}
      version: ${{ steps.changelog.outputs.version }}

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: |
          echo "Output1: ${{ needs.job1.outputs.output1 }}"
          echo "Output2: ${{ needs.job1.outputs.output2 }}"
          echo "Tagname: ${{ needs.job1.outputs.output3 }}"
          echo "Contents: ${{ needs.job1.outputs.output4 }}"
          echo "Changelog: ${{ needs.job1.outputs.changelog }}"
          echo "Clean Changelog: ${{ needs.job1.outputs.clean_changelog }}"
          echo "Version: ${{ needs.job1.outputs.version }}"

  job3:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: my-artifact  # Use the artifact name "my-artifact" to download

      - name: Use the Artifact
        run: |
          cat hello.txt  # Displaying the content of the downloaded artifact

  test-run:
    runs-on: ubuntu-latest
    needs: job3
    steps:
      - name: Download candidate artifacts
        uses: actions/download-artifact@v3
        with:
          name: my-artifact  # Correct name of artifact to download

      - run: |
          echo "Hello, World" >> hello.txt
          cat hello.txt
