name: Python application

on:
  workflow_dispatch: # Allows mannually running the workflow
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Checkout the repository

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.12.2'  # Specify the Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # Upgrade pip
        pip install -r requirements.txt  # Install dependencies from a requirements file

    - name: Run the script
      run: |
        python src/main.py  # Run the Python script
