name: Python application

on:
  workflow_dispatch:  # Allows manually running the workflow
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

env:
  GLOBAL_VAR: "global_value"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Checkout the repository

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.12.2'  # Specify the Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # Upgrade pip
        pip install -r requirements.txt  # Install dependencies from a requirements file

    - name: Run the script
      env:
        MY_SECRET_KEY: ${{ secrets.MY_SECRET_KEY }}
      run: |
        echo "Running with the secret..."
        python src/main.py  # Run the Python script

    - name: Display global environment variable
      run: echo "Global variable: $GLOBAL_VAR"