name: Python application run by @${{ github.actor }}

on: 
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Checkout the repository

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.2'  # Specify the Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # Upgrade pip

    - name: Run the script
      run: |
        python src/main.py  # Run the Python script
